### ISSUE TITLE
4 Waterloo-region image hotlinks are pointing to wrong file

### ISSUE THREAD

**Issue by onassar** [opennorth/represent-canada-data#26]
See here: ![](https://i.imgur.com/4Ys4wOO.png)
Steps to reproduce:

1. Visit http://opennorth.github.io/jquery-findyourrep-ca/
2. Enter "428 Sandbrook Crescent, Waterloo" as the address

Specifically, the following three image links ought to point to other resources:
http://www.regionofwaterloo.ca/en/regionalGovernment/seanstrickland.asp -> http://www.regionofwaterloo.ca/en/regionalGovernment/resources/STRICKLAND_IMG_3890RV.jpg

http://www.regionofwaterloo.ca/en/regionalGovernment/regionalchairandsupportstaff.asp -> http://www.regionofwaterloo.ca/en/regionalGovernment/resources/Meet%20Ken%20Seiling%20Informal%20Pose%20Web%20Pic.jpg

http://www.regionofwaterloo.ca/en/regionalGovernment/janemitchell.asp -> http://www.regionofwaterloo.ca/en/regionalGovernment/resources/Jane%20Mitchell%20Web%20Pic.jpg

The second broken-image in the above screenshot for Dave Jaworsky does not have an `src` value.

**Comment by jpmckinney** [comment]
Thanks - can you re-open on this repo? https://github.com/opencivicdata/scrapers-ca/
