### ISSUE TITLE
clarifying maintenance

### ISSUE THREAD

**Issue by cmyr** [opennorth/represent-canada-data#27]
Going through the maintenance tasks here, which I haven't really done before, and having some confusion.

- `invoke definitions` fails with an exception in an OCD package, but I'm not sure what the fix should be. Can open an issue there if I'm not missing anything?

```
 File "opennorth/represent-canada-data/tasks.py", line 336, in definitions
    expected_slug, expected_config = get_definition(division_id, path=config['file'])
  File "opennorth/represent-canada-data/tasks.py", line 105, in get_definition
    division = Division.get(division_id, from_csv=ocd_division_csv)
  File "represent-env/lib/python3.6/site-packages/opencivicdata/divisions.py", line 56, in get
    for d in self.all(country, from_csv):
UnboundLocalError: local variable 'country' referenced before assignment
```

- when I run `invoke shapefiles --base=SOME/BASE` I end up with new untracked files in a particular `boundaries` subdir. I presume these are supposed to replace existing files? This isn't mentioned in any of the docs that I could find. 

- It is unclear if the 'Process shapefiles' maintenance step is required after updates, or only when certain things change, or only when adding new datasets?

**Comment by jpmckinney** [comment]
1. I opened a PR to fix that: https://github.com/opencivicdata/python-opencivicdata/pull/112
1. Yes, sometimes the source changes file names. You should see untracked files, and deleted files. I just `git add` that subdirectory, but you should [process that new shapefile](https://github.com/opennorth/represent-canada-data#process-shapefiles) first. I'll add instructions about when to add files to Git.
1. Process all shapefiles if files other than `definition.py` where changed by `invoke shapefiles`. I'll add instructions about this.
