### ISSUE TITLE
alberta electoral districts 2019 redistribution

### ISSUE THREAD

**Issue by KarinG** [opennorth/represent-canada-data#28]
To help prep for upcoming elections - would be super helpful to be able to retrieve

the newly approved: 
`boundary-sets/alberta-electoral-districts-2019-redistribution`
http://www.elections.ab.ca/wp-content/uploads/2019Boundaries_ED-Shapefiles.zip

in addition to the currently active one:
`boundary-sets/alberta-electoral-districts`

@jpmckinney - please let us know how we may be able to help make this happen. Perhaps we can help fund this - or would you consider a PR?

Cc: @adixon

**Comment by jpmckinney** [comment]
PRs are always welcome!

In this case, I added the set, now available at: http://represent.opennorth.ca/boundary-sets/alberta-electoral-districts-2017/

**Comment by KarinG** [comment]
Awesome! :-)

**Comment by KarinG** [comment]
PS - hold on the new set is available at ... 2017?

**Comment by jpmckinney** [comment]
We use the year of the boundary commission: http://www.elections.ab.ca/resources/legislation/the-boundaries-commission-act/

**Comment by KarinG** [comment]
Ah - understood. Thank you!
