### ISSUE TITLE
No MLAs for Canadian Territories?

### ISSUE THREAD

**Issue by jtheletter** [opennorth/represent-canada-data#32]
I've noticed if I search your website's demo app (https://represent.opennorth.ca/demo/) for addresses in Northwest, Nunavut, or Yukon territories, I only see MPs, no MLAs. Is there a way to correct that? Thank you.

**Comment by jpmckinney** [comment]
The electoral offices of the territories unfortunately have not shared their geospatial electorial boundaries with us, so we can't offer lookups for the territories.

**Comment by jpmckinney** [comment]
Noting that NT was added October 2015, so a scraper can be written to collect the representatives.
