### ISSUE TITLE
ERROR: opencivicdata 3.2.0 has requirement Django>=2.2, but you'll have django 1.11.29 which is incompatible

### ISSUE THREAD

**Issue by imhangoo** [opennorth/represent-canada-data#34]
This error happens after running command:
pip install -r requirements.txt flake8

I tried to search the code, seems like django package is not used.

**Comment by jpmckinney** [comment]
Sorry, I wasn't subscribed to new issue notifications. You probably just need to upgrade pip, which has better version compatibility resolution.
