### ISSUE TITLE
2024 Electoral District Boundaries for BC

### ISSUE THREAD

**Issue by KarinG** [opennorth/represent-canada-data#45]
Could you please add the new 2024 Electoral District Boundaries for British Columbia?

The final shapefiles are here: 

https://bcebc.ca/maps-and-resources/

**Comment by jpmckinney** [comment]
I've contacted Elections BC about adding them to the data catalogue: https://catalogue.data.gov.bc.ca/dataset/current-provincial-electoral-districts-of-british-columbia

Otherwise it's a bit of a rigamarole to add unlicensed data.

**Comment by KarinG** [comment]
Thank you!

**Comment by jpmckinney** [comment]
Added!

**Comment by KarinG** [comment]
Thank you!
